#include <stdio.h>
#include "dunkasm.h"

const dunk_instr dunk_instrs[N_INSTR] = {
	NULLARY_INSTR("chill",	0x00),
	
	//**flow control**//
	UNARY___INSTR("goto",					0x01, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("goto_if_zero",			0x02, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("goto_if_nonzero",		0x03, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("goto_if_negative",		0x04, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("goto_if_nonnegative",	0x05, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("goto_if_positive",		0x06, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("goto_if_nonpositive",	0x07, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_equal",			0x08, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_unequal",		0x09, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_less",			0x0a, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_greater",		0x0b, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_leq",			0x0c, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_geq",			0x0d, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_equal",			0x0e, REGISTER, FIRST_NIBBLE, CONSTANT,  FOLLOWING(2), CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_unequal",		0x0f, REGISTER, FIRST_NIBBLE, CONSTANT,  FOLLOWING(2), CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_less",			0x10, REGISTER, FIRST_NIBBLE, CONSTANT,  FOLLOWING(2), CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_greater",		0x11, REGISTER, FIRST_NIBBLE, CONSTANT,  FOLLOWING(2), CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_leq",			0x12, REGISTER, FIRST_NIBBLE, CONSTANT,  FOLLOWING(2), CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_geq",			0x13, REGISTER, FIRST_NIBBLE, CONSTANT,  FOLLOWING(2), CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_less_unsgn",		0x14, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_greater_unsgn",	0x15, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_leq_unsgn",		0x16, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_geq_unsgn",		0x17, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_equal_unsgn",	0x18, REGISTER, FIRST_NIBBLE, CONSTANT,  FOLLOWING(2), CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_unequal_unsgn",	0x19, REGISTER, FIRST_NIBBLE, CONSTANT,  FOLLOWING(2), CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_less_unsgn",		0x1a, REGISTER, FIRST_NIBBLE, CONSTANT,  FOLLOWING(2), CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_greater_unsgn",	0x1b, REGISTER, FIRST_NIBBLE, CONSTANT,  FOLLOWING(2), CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_leq_unsgn",		0x1c, REGISTER, FIRST_NIBBLE, CONSTANT,  FOLLOWING(2), CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_geq_unsgn",		0x1d, REGISTER, FIRST_NIBBLE, CONSTANT,  FOLLOWING(2), CONSTANT, FOLLOWING(1)),

	//**setting**//
	BINARY__INSTR("swap",	0x1e, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	
	BINARY__INSTR("set",	0x1f, CONSTANT | POINTER, FOLLOWING(1), CONSTANT, FOLLOWING(2)),
	BINARY__INSTR("set",	0x20, CONSTANT | POINTER, FOLLOWING(1), CONSTANT | POINTER, FOLLOWING(2)),

	BINARY__INSTR("set",	0x21, CONSTANT | POINTER, FOLLOWING(1), REGISTER, FIRST_NIBBLE),
	BINARY__INSTR("set",	0x22, CONSTANT | POINTER, FOLLOWING(1), REGISTER | POINTER, FIRST_NIBBLE),
	BINARY__INSTR("set",	0x23, CONSTANT | POINTER, FOLLOWING(1), REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | FOLLOWING(2)),

	BINARY__INSTR("set",	0x24, CONSTANT | POINTER, FOLLOWING(1), S_REGISTER, FIRST_NIBBLE),
	BINARY__INSTR("set",	0x25, CONSTANT | POINTER, FOLLOWING(1), S_REGISTER | POINTER, FIRST_NIBBLE),
	BINARY__INSTR("set",	0x26, CONSTANT | POINTER, FOLLOWING(1), S_REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | FOLLOWING(2)),

	BINARY__INSTR("set",	0x27, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("set",	0x28, REGISTER, FIRST_NIBBLE, CONSTANT | POINTER, FOLLOWING(1)),

	BINARY__INSTR("set",	0x29, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x2a, REGISTER, FIRST_NIBBLE, REGISTER | POINTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x2b, REGISTER, FIRST_NIBBLE, REGISTER | POINTER | W_OFFSET, SECOND_NIBBLE | OFFSET_FOLLOWING(1)),
	
	BINARY__INSTR("set",	0x2c, REGISTER, FIRST_NIBBLE, S_REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x2d, REGISTER, FIRST_NIBBLE, S_REGISTER | POINTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x2e, REGISTER, FIRST_NIBBLE, S_REGISTER | POINTER | W_OFFSET, SECOND_NIBBLE | OFFSET_FOLLOWING(1)),

	BINARY__INSTR("set",	0x2f, REGISTER | POINTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("set",	0x30, REGISTER | POINTER, FIRST_NIBBLE, CONSTANT | POINTER, FOLLOWING(1)),

	BINARY__INSTR("set",	0x31, REGISTER | POINTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x32, REGISTER | POINTER, FIRST_NIBBLE, REGISTER | POINTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x33, REGISTER | POINTER, FIRST_NIBBLE, REGISTER | POINTER | W_OFFSET, SECOND_NIBBLE | OFFSET_FOLLOWING(1)),

	BINARY__INSTR("set",	0x34, REGISTER | POINTER, FIRST_NIBBLE, S_REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x35, REGISTER | POINTER, FIRST_NIBBLE, S_REGISTER | POINTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x36, REGISTER | POINTER, FIRST_NIBBLE, S_REGISTER | POINTER | W_OFFSET, SECOND_NIBBLE | OFFSET_FOLLOWING(1)),

	BINARY__INSTR("set",	0x37, REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), CONSTANT, FOLLOWING(2)),
	BINARY__INSTR("set",	0x38, REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), CONSTANT | POINTER, FOLLOWING(2)),

	BINARY__INSTR("set",	0x39, REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x3a, REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), REGISTER | POINTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x3b, REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), REGISTER | POINTER | W_OFFSET, SECOND_NIBBLE | OFFSET_FOLLOWING(2)),

	BINARY__INSTR("set",	0x3c, REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), S_REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x3d, REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), S_REGISTER | POINTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x3e, REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), S_REGISTER | POINTER | W_OFFSET, SECOND_NIBBLE | OFFSET_FOLLOWING(2)),
	
	BINARY__INSTR("set",	0x3f, S_REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("set",	0x40, S_REGISTER, FIRST_NIBBLE, CONSTANT | POINTER, FOLLOWING(1)),

	BINARY__INSTR("set",	0x41, S_REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x42, S_REGISTER, FIRST_NIBBLE, REGISTER | POINTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x43, S_REGISTER, FIRST_NIBBLE, REGISTER | POINTER | W_OFFSET, SECOND_NIBBLE | OFFSET_FOLLOWING(1)),

	BINARY__INSTR("set",	0x44, S_REGISTER, FIRST_NIBBLE, S_REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x45, S_REGISTER, FIRST_NIBBLE, S_REGISTER | POINTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x46, S_REGISTER, FIRST_NIBBLE, S_REGISTER | POINTER | W_OFFSET, SECOND_NIBBLE | OFFSET_FOLLOWING(1)),

	BINARY__INSTR("set",	0x47, S_REGISTER | POINTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("set",	0x48, S_REGISTER | POINTER, FIRST_NIBBLE, CONSTANT | POINTER, FOLLOWING(1)),

	BINARY__INSTR("set",	0x49, S_REGISTER | POINTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x4a, S_REGISTER | POINTER, FIRST_NIBBLE, REGISTER | POINTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x4b, S_REGISTER | POINTER, FIRST_NIBBLE, REGISTER | POINTER | W_OFFSET, SECOND_NIBBLE | OFFSET_FOLLOWING(1)),

	BINARY__INSTR("set",	0x4c, S_REGISTER | POINTER, FIRST_NIBBLE, S_REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x4d, S_REGISTER | POINTER, FIRST_NIBBLE, S_REGISTER | POINTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x4e, S_REGISTER | POINTER, FIRST_NIBBLE, S_REGISTER | POINTER | W_OFFSET, SECOND_NIBBLE | OFFSET_FOLLOWING(1)),

	BINARY__INSTR("set",	0x4f, S_REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), CONSTANT, FOLLOWING(2)),
	BINARY__INSTR("set",	0x50, S_REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), CONSTANT | POINTER, FOLLOWING(2)),

	BINARY__INSTR("set",	0x51, S_REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x52, S_REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), REGISTER | POINTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x53, S_REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), REGISTER | POINTER | W_OFFSET, SECOND_NIBBLE | OFFSET_FOLLOWING(2)),

	BINARY__INSTR("set",	0x54, S_REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), S_REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x55, S_REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), S_REGISTER | POINTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x56, S_REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), S_REGISTER | POINTER | W_OFFSET, SECOND_NIBBLE | OFFSET_FOLLOWING(2)),

	//**ALU**//
	UNARY___INSTR("neg",	0x57, REGISTER, FIRST_NIBBLE | SECOND_NIBBLE),
	UNARY___INSTR("inc",	0x58, REGISTER, FIRST_NIBBLE | SECOND_NIBBLE),
	UNARY___INSTR("dec",	0x59, REGISTER, FIRST_NIBBLE | SECOND_NIBBLE),
	UNARY___INSTR("sgn",	0x5a, REGISTER, FIRST_NIBBLE | SECOND_NIBBLE),
	UNARY___INSTR("not",	0x5b, REGISTER, FIRST_NIBBLE | SECOND_NIBBLE),
	UNARY___INSTR("lshift",	0x5c, REGISTER, FIRST_NIBBLE | SECOND_NIBBLE),
	UNARY___INSTR("rshift",	0x5d, REGISTER, FIRST_NIBBLE | SECOND_NIBBLE),
	
	BINARY__INSTR("neg",	0x5e, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("inc",	0x5f, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("dec",	0x60, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("sgn",	0x61, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("not",	0x62, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("lshift",	0x63, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("rshift",	0x64, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	
	BINARY__INSTR("add",	0x65, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("sub",	0x66, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),	
	BINARY__INSTR("mul",	0x67, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("ucmp",	0x68, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("cmp",	0x69, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("and",	0x6a, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("or",		0x6b, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("xor",	0x6c, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("shift",	0x6d, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	
	TERNARY_INSTR("add",	0x6e, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("sub",	0x6f, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),	
	TERNARY_INSTR("mul",	0x70, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("ucmp",	0x71, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("cmp",	0x72, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("and",	0x73, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("or",		0x74, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("xor",	0x75, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("shift",	0x76, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	
	BINARY__INSTR("add",	0x77, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("sub",	0x78, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),	
	BINARY__INSTR("mul",	0x79, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("ucmp",	0x7a, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("cmp",	0x7b, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("and",	0x7c, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("or",		0x7d, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("xor",	0x7e, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("shift",	0x7f, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	
	TERNARY_INSTR("add",	0x80, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, REGISTER, FOLLOWING(1)),
	TERNARY_INSTR("sub",	0x81, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, REGISTER, FOLLOWING(1)),	
	TERNARY_INSTR("mul",	0x82, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, REGISTER, FOLLOWING(1)),
	TERNARY_INSTR("ucmp",	0x83, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, REGISTER, FOLLOWING(1)),
	TERNARY_INSTR("cmp",	0x84, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, REGISTER, FOLLOWING(1)),
	TERNARY_INSTR("and",	0x85, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, REGISTER, FOLLOWING(1)),
	TERNARY_INSTR("or",		0x86, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, REGISTER, FOLLOWING(1)),
	TERNARY_INSTR("xor",	0x87, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, REGISTER, FOLLOWING(1)),
	TERNARY_INSTR("shift",	0x88, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, REGISTER, FOLLOWING(1)),

	//**stack stuff**//

	// pushes
	NULLARY_INSTR("push",	0x89),
	UNARY___INSTR("push",	0x8a, CONSTANT, FOLLOWING(1)),
	UNARY___INSTR("push",	0x8b, CONSTANT | POINTER, FOLLOWING(1)),
	UNARY___INSTR("push",	0x8c, REGISTER, FIRST_NIBBLE),
	UNARY___INSTR("push",	0x8d, REGISTER | POINTER, FIRST_NIBBLE),
	UNARY___INSTR("push",	0x8e, REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1)),
	UNARY___INSTR("push",	0x8f, S_REGISTER, FIRST_NIBBLE),
	UNARY___INSTR("push",	0x90, S_REGISTER | POINTER, FIRST_NIBBLE),
	UNARY___INSTR("push",	0x91, S_REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1)),

	// pops
	NULLARY_INSTR("pop",	0x92),
	UNARY___INSTR("pop",	0x93, CONSTANT | POINTER, FOLLOWING(1)),
	UNARY___INSTR("pop",	0x94, REGISTER, FIRST_NIBBLE),
	UNARY___INSTR("pop",	0x95, REGISTER | POINTER, FIRST_NIBBLE),
	UNARY___INSTR("pop",	0x96, REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1)),
	UNARY___INSTR("pop",	0x97, S_REGISTER, FIRST_NIBBLE),
	UNARY___INSTR("pop",	0x98, S_REGISTER | POINTER, FIRST_NIBBLE),
	UNARY___INSTR("pop",	0x99, S_REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1)),
	
	// function stuff
	UNARY___INSTR("call",	0x9a, CONSTANT, FOLLOWING(1)),
	
	NULLARY_INSTR("return",	0x9b),
	
	// I/O pins
	UNARY___INSTR("pinmode_input",		0x9c, CONSTANT, FIRST_NIBBLE),
	UNARY___INSTR("pinmode_output",		0x9d, CONSTANT, FIRST_NIBBLE),
	
	UNARY___INSTR("pinmode_input",		0x9e, REGISTER, FIRST_NIBBLE),
	UNARY___INSTR("pinmode_output",		0x9f, REGISTER, FIRST_NIBBLE),
	
	UNARY___INSTR("set_pin_low",		0xa0, CONSTANT, FIRST_NIBBLE),
	UNARY___INSTR("set_pin_high",		0xa1, CONSTANT, FIRST_NIBBLE),
	
	UNARY___INSTR("set_pin_low",		0xa2, REGISTER, FIRST_NIBBLE),
	UNARY___INSTR("set_pin_high",		0xa3, REGISTER, FIRST_NIBBLE),
	
	BINARY__INSTR("read_pin",			0xa4, CONSTANT, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("write_pin",			0xa5, CONSTANT, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	
	BINARY__INSTR("read_pin",			0xa6, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("write_pin",			0xa7, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	
	// important stuff
	NULLARY_INSTR("handle_interrupt",		0xfe);
	NULLARY_INSTR("halt_and_catch_fire",	0xff)
};
