#include <stdio.h>
#include "dunkasm.h"

dunk_instr dunk_instrs[N_INSTR] = {
	NULLARY_COMMAND("chill", 0x00),

	//**setting**//
	BINARY__COMMAND("set", 0x10, CONSTANT | POINTER, FOLLOWING(1), CONSTANT, FOLLOWING(2)),
	BINARY__COMMAND("set", 0x11, CONSTANT | POINTER, FOLLOWING(1), CONSTANT | POINTER, FOLLOWING(2)),

	BINARY__COMMAND("set", 0x12, CONSTANT | POINTER, FOLLOWING(1), REGISTER, FIRST_NIBBLE),
	BINARY__COMMAND("set", 0x13, CONSTANT | POINTER, FOLLOWING(1), REGISTER | POINTER, FIRST_NIBBLE),
	BINARY__COMMAND("set", 0x14, CONSTANT | POINTER, FOLLOWING(1), REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | FOLLOWING(2)),

	BINARY__COMMAND("set", 0x15, CONSTANT | POINTER, FOLLOWING(1), S_REGISTER, FIRST_NIBBLE),
	BINARY__COMMAND("set", 0x16, CONSTANT | POINTER, FOLLOWING(1), S_REGISTER | POINTER, FIRST_NIBBLE),
	BINARY__COMMAND("set", 0x17, CONSTANT | POINTER, FOLLOWING(1), S_REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | FOLLOWING(2)),

	BINARY__COMMAND("set", 0x18, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__COMMAND("set", 0x19, REGISTER, FIRST_NIBBLE, CONSTANT | POINTER, FOLLOWING(1)),

	BINARY__COMMAND("set", 0x1a, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__COMMAND("set", 0x1b, REGISTER, FIRST_NIBBLE, REGISTER | POINTER, SECOND_NIBBLE),
	BINARY__COMMAND("set", 0x1c, REGISTER, FIRST_NIBBLE, REGISTER | POINTER | W_OFFSET, SECOND_NIBBLE | OFFSET_FOLLOWING(1)),
	
	BINARY__COMMAND("set", 0x1e, REGISTER, FIRST_NIBBLE, S_REGISTER, SECOND_NIBBLE),
	BINARY__COMMAND("set", 0x1f, REGISTER, FIRST_NIBBLE, S_REGISTER | POINTER, SECOND_NIBBLE),
	BINARY__COMMAND("set", 0x20, REGISTER, FIRST_NIBBLE, S_REGISTER | POINTER | W_OFFSET, SECOND_NIBBLE | OFFSET_FOLLOWING(1)),

	BINARY__COMMAND("set", 0x21, REGISTER | POINTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__COMMAND("set", 0x22, REGISTER | POINTER, FIRST_NIBBLE, CONSTANT | POINTER, FOLLOWING(1)),

	BINARY__COMMAND("set", 0x23, REGISTER | POINTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__COMMAND("set", 0x24, REGISTER | POINTER, FIRST_NIBBLE, REGISTER | POINTER, SECOND_NIBBLE),
	BINARY__COMMAND("set", 0x25, REGISTER | POINTER, FIRST_NIBBLE, REGISTER | POINTER | W_OFFSET, SECOND_NIBBLE | OFFSET_FOLLOWING(1)),

	BINARY__COMMAND("set", 0x26, REGISTER | POINTER, FIRST_NIBBLE, S_REGISTER, SECOND_NIBBLE),
	BINARY__COMMAND("set", 0x27, REGISTER | POINTER, FIRST_NIBBLE, S_REGISTER | POINTER, SECOND_NIBBLE),
	BINARY__COMMAND("set", 0x28, REGISTER | POINTER, FIRST_NIBBLE, S_REGISTER | POINTER | W_OFFSET, SECOND_NIBBLE | OFFSET_FOLLOWING(1)),

	BINARY__COMMAND("set", 0x29, REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), CONSTANT, FOLLOWING(2)),
	BINARY__COMMAND("set", 0x2a, REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), CONSTANT | POINTER, FOLLOWING(2)),

	BINARY__COMMAND("set", 0x2b, REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), REGISTER, SECOND_NIBBLE),
	BINARY__COMMAND("set", 0x2c, REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), REGISTER | POINTER, SECOND_NIBBLE),
	BINARY__COMMAND("set", 0x2d, REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), REGISTER | POINTER | W_OFFSET, SECOND_NIBBLE | OFFSET_FOLLOWING(2)),

	BINARY__COMMAND("set", 0x2e, REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), S_REGISTER, SECOND_NIBBLE),
	BINARY__COMMAND("set", 0x2f, REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), S_REGISTER | POINTER, SECOND_NIBBLE),
	BINARY__COMMAND("set", 0x30, REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), S_REGISTER | POINTER | W_OFFSET, SECOND_NIBBLE | OFFSET_FOLLOWING(2)),
	
	BINARY__COMMAND("set", 0x31, S_REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__COMMAND("set", 0x32, S_REGISTER, FIRST_NIBBLE, CONSTANT | POINTER, FOLLOWING(1)),

	BINARY__COMMAND("set", 0x33, S_REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__COMMAND("set", 0x34, S_REGISTER, FIRST_NIBBLE, REGISTER | POINTER, SECOND_NIBBLE),
	BINARY__COMMAND("set", 0x35, S_REGISTER, FIRST_NIBBLE, REGISTER | POINTER | W_OFFSET, SECOND_NIBBLE | OFFSET_FOLLOWING(1)),

	BINARY__COMMAND("set", 0x36, S_REGISTER, FIRST_NIBBLE, S_REGISTER, SECOND_NIBBLE),
	BINARY__COMMAND("set", 0x37, S_REGISTER, FIRST_NIBBLE, S_REGISTER | POINTER, SECOND_NIBBLE),
	BINARY__COMMAND("set", 0x38, S_REGISTER, FIRST_NIBBLE, S_REGISTER | POINTER | W_OFFSET, SECOND_NIBBLE | OFFSET_FOLLOWING(1)),

	BINARY__COMMAND("set", 0x39, S_REGISTER | POINTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__COMMAND("set", 0x3a, S_REGISTER | POINTER, FIRST_NIBBLE, CONSTANT | POINTER, FOLLOWING(1)),

	BINARY__COMMAND("set", 0x3b, S_REGISTER | POINTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__COMMAND("set", 0x3c, S_REGISTER | POINTER, FIRST_NIBBLE, REGISTER | POINTER, SECOND_NIBBLE),
	BINARY__COMMAND("set", 0x3d, S_REGISTER | POINTER, FIRST_NIBBLE, REGISTER | POINTER | W_OFFSET, SECOND_NIBBLE | OFFSET_FOLLOWING(1)),

	BINARY__COMMAND("set", 0x3e, S_REGISTER | POINTER, FIRST_NIBBLE, S_REGISTER, SECOND_NIBBLE),
	BINARY__COMMAND("set", 0x3f, S_REGISTER | POINTER, FIRST_NIBBLE, S_REGISTER | POINTER, SECOND_NIBBLE),
	BINARY__COMMAND("set", 0x40, S_REGISTER | POINTER, FIRST_NIBBLE, S_REGISTER | POINTER | W_OFFSET, SECOND_NIBBLE | OFFSET_FOLLOWING(1)),

	BINARY__COMMAND("set", 0x41, S_REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), CONSTANT, FOLLOWING(2)),
	BINARY__COMMAND("set", 0x42, S_REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), CONSTANT | POINTER, FOLLOWING(2)),

	BINARY__COMMAND("set", 0x43, S_REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), REGISTER, SECOND_NIBBLE),
	BINARY__COMMAND("set", 0x44, S_REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), REGISTER | POINTER, SECOND_NIBBLE),
	BINARY__COMMAND("set", 0x45, S_REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), REGISTER | POINTER | W_OFFSET, SECOND_NIBBLE | OFFSET_FOLLOWING(2)),

	BINARY__COMMAND("set", 0x46, S_REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), S_REGISTER, SECOND_NIBBLE),
	BINARY__COMMAND("set", 0x47, S_REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), S_REGISTER | POINTER, SECOND_NIBBLE),
	BINARY__COMMAND("set", 0x48, S_REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1), S_REGISTER | POINTER | W_OFFSET, SECOND_NIBBLE | OFFSET_FOLLOWING(2)),

	//**ALU**//
	BINARY__COMMAND("add", 		0x50, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__COMMAND("sub", 		0x51, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),	
	BINARY__COMMAND("subtract", 0x51, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__COMMAND("mul", 		0x52, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__COMMAND("multiply", 0x52, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),

	UNARY___COMMAND("increment", 0x53, REGISTER, FIRST_NIBBLE | SECOND_NIBBLE),
	UNARY___COMMAND("decrement", 0x54, REGISTER, FIRST_NIBBLE | SECOND_NIBBLE),
	UNARY___COMMAND("negate", 	 0x55, REGISTER, FIRST_NIBBLE | SECOND_NIBBLE),

	BINARY__COMMAND("compare_unsigned", 0x56, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__COMMAND("compare",			0x57, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),

	UNARY___COMMAND("sign", 0x58, REGISTER, FIRST_NIBBLE | SECOND_NIBBLE),

	BINARY__COMMAND("and",  0x59, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__COMMAND("or",	0x5a, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__COMMAND("xor",	0x5b, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__COMMAND("not",	0x5c, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),

	UNARY___COMMAND("lshift", 0x5d, REGISTER, FIRST_NIBBLE | SECOND_NIBBLE),
	BINARY__COMMAND("shift",  0x5d, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	UNARY___COMMAND("rshift", 0x5e, REGISTER, FIRST_NIBBLE | SECOND_NIBBLE),

	//**stack stuff**//

	// pushes
	NULLARY_COMMAND("push", 0x60),
	UNARY___COMMAND("push", 0x61, CONSTANT, FOLLOWING(1)),
	UNARY___COMMAND("push", 0x62, CONSTANT | POINTER, FOLLOWING(1)),
	UNARY___COMMAND("push", 0x63, REGISTER, FIRST_NIBBLE),
	UNARY___COMMAND("push", 0x64, REGISTER | POINTER, FIRST_NIBBLE),
	UNARY___COMMAND("push", 0x65, REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1)),
	UNARY___COMMAND("push", 0x66, S_REGISTER, FIRST_NIBBLE),
	UNARY___COMMAND("push", 0x67, S_REGISTER | POINTER, FIRST_NIBBLE),
	UNARY___COMMAND("push", 0x68, S_REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1)),

	// pops
	NULLARY_COMMAND("pop", 0x69),
	UNARY___COMMAND("pop", 0x6a, CONSTANT | POINTER, FOLLOWING(1)),
	UNARY___COMMAND("pop", 0x6b, REGISTER, FIRST_NIBBLE),
	UNARY___COMMAND("pop", 0x6c, REGISTER | POINTER, FIRST_NIBBLE),
	UNARY___COMMAND("pop", 0x6d, REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1)),
	UNARY___COMMAND("pop", 0x6e, S_REGISTER, FIRST_NIBBLE),
	UNARY___COMMAND("pop", 0x69, S_REGISTER | POINTER, FIRST_NIBBLE),
	UNARY___COMMAND("pop", 0x70, S_REGISTER | POINTER | W_OFFSET, FIRST_NIBBLE | OFFSET_FOLLOWING(1)),
	
	// function stuff
	CALL_COMMAND("call", 0x80, 0),
	CALL_COMMAND("call", 0x81, 1),
	CALL_COMMAND("call", 0x82, 2),
	CALL_COMMAND("call", 0x83, 3),
	CALL_COMMAND("call", 0x84, 4),
	CALL_COMMAND("call", 0x85, 5),
	CALL_COMMAND("call", 0x86, 6),
	CALL_COMMAND("call", 0x87, 7),
	CALL_COMMAND("call", 0x88, 8),
	
	RET_COMMAND("return", 0x90, 0),
	RET_COMMAND("return", 0x91, 1),
	RET_COMMAND("return", 0x92, 2),
	RET_COMMAND("return", 0x93, 3),
	RET_COMMAND("return", 0x94, 4),
	RET_COMMAND("return", 0x95, 5),
	RET_COMMAND("return", 0x96, 6),
	RET_COMMAND("return", 0x97, 7),
	RET_COMMAND("return", 0x98, 8),
	
	// I/O pins
	UNARY___COMMAND("pinmode_input",  0xa0, CONSTANT, FIRST_NIBBLE),
	UNARY___COMMAND("pinmode_output", 0xa1, CONSTANT, FIRST_NIBBLE),
	
	UNARY___COMMAND("pinmode_input",  0xa2, REGISTER, FIRST_NIBBLE),
	UNARY___COMMAND("pinmode_output", 0xa3, REGISTER, FIRST_NIBBLE),
	
	UNARY___COMMAND("set_pin_low",  0xa4, CONSTANT, FIRST_NIBBLE),
	UNARY___COMMAND("set_pin_high", 0xa5, CONSTANT, FIRST_NIBBLE),
	
	UNARY___COMMAND("set_pin_low",  0xa6, REGISTER, FIRST_NIBBLE),
	UNARY___COMMAND("set_pin_high", 0xa7, REGISTER, FIRST_NIBBLE),
	
	BINARY__COMMAND("read_pin",  0xa8, CONSTANT, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__COMMAND("write_pin", 0xa9, CONSTANT, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	
	BINARY__COMMAND("read_pin",  0xaa, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__COMMAND("write_pin", 0xab, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	
	NULLARY_COMMAND("halt_and_catch_fire", 0xff)
};
