#include <string.h>
#include <stdio.h>
#include "dunkasm.h"

const dunk_instr dunk_instrs[N_INSTR] = {
	NULLARY_INSTR("chill",	0x00),
	
	//**flow control**//
	UNARY___INSTR("goto",					0x01, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("goto_if_zero",			0x02, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("goto_if_nonzero",		0x03, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("goto_if_negative",		0x04, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("goto_if_nonnegative",	0x05, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("goto_if_positive",		0x06, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("goto_if_nonpositive",	0x07, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_equal",			0x08, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_unequal",		0x09, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_less",			0x0a, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_greater",		0x0b, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_leq",			0x0c, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_geq",			0x0d, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_equal",			0x0e, REGISTER, FIRST_NIBBLE, CONSTANT,  FOLLOWING(2), CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_unequal",		0x0f, REGISTER, FIRST_NIBBLE, CONSTANT,  FOLLOWING(2), CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_less",			0x10, REGISTER, FIRST_NIBBLE, CONSTANT,  FOLLOWING(2), CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_greater",		0x11, REGISTER, FIRST_NIBBLE, CONSTANT,  FOLLOWING(2), CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_leq",			0x12, REGISTER, FIRST_NIBBLE, CONSTANT,  FOLLOWING(2), CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_geq",			0x13, REGISTER, FIRST_NIBBLE, CONSTANT,  FOLLOWING(2), CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_less_unsgn",		0x14, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_greater_unsgn",	0x15, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_leq_unsgn",		0x16, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_geq_unsgn",		0x17, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_equal_unsgn",	0x18, REGISTER, FIRST_NIBBLE, CONSTANT,  FOLLOWING(2), CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_unequal_unsgn",	0x19, REGISTER, FIRST_NIBBLE, CONSTANT,  FOLLOWING(2), CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_less_unsgn",		0x1a, REGISTER, FIRST_NIBBLE, CONSTANT,  FOLLOWING(2), CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_greater_unsgn",	0x1b, REGISTER, FIRST_NIBBLE, CONSTANT,  FOLLOWING(2), CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_leq_unsgn",		0x1c, REGISTER, FIRST_NIBBLE, CONSTANT,  FOLLOWING(2), CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("goto_if_geq_unsgn",		0x1d, REGISTER, FIRST_NIBBLE, CONSTANT,  FOLLOWING(2), CONSTANT, FOLLOWING(1)),

	//**setting**//
	BINARY__INSTR("swap",	0x1e, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	
	BINARY__INSTR("set",	0x1f, CONSTANT | POINTER, FOLLOWING(1), CONSTANT, FOLLOWING(2)),
	BINARY__INSTR("set",	0x20, CONSTANT | POINTER, FOLLOWING(1), CONSTANT | POINTER, FOLLOWING(2)),

	BINARY__INSTR("set",	0x21, CONSTANT | POINTER, FOLLOWING(1), REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x22, CONSTANT | POINTER, FOLLOWING(2), REGISTER | POINTER, SECOND_NIBBLE | OFFSET_FOLLOWING(1)),

	BINARY__INSTR("set",	0x23, CONSTANT | POINTER, FOLLOWING(1), S_REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x24, CONSTANT | POINTER, FOLLOWING(2), S_REGISTER | POINTER, SECOND_NIBBLE | OFFSET_FOLLOWING(1)),



	BINARY__INSTR("set",	0x25, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("set",	0x26, REGISTER, FIRST_NIBBLE, CONSTANT | POINTER, FOLLOWING(1)),

	BINARY__INSTR("set",	0x27, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x28, REGISTER, FIRST_NIBBLE, REGISTER | POINTER, SECOND_NIBBLE | OFFSET_FOLLOWING(1)),
	
	BINARY__INSTR("set",	0x29, REGISTER, FIRST_NIBBLE, S_REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x2a, REGISTER, FIRST_NIBBLE, S_REGISTER | POINTER, SECOND_NIBBLE | OFFSET_FOLLOWING(1)),

	BINARY__INSTR("set",	0x2b, REGISTER | POINTER, FIRST_NIBBLE | OFFSET_FOLLOWING(1), CONSTANT, FOLLOWING(2)),
	BINARY__INSTR("set",	0x2c, REGISTER | POINTER, FIRST_NIBBLE | OFFSET_FOLLOWING(1), CONSTANT | POINTER, OFFSET_FOLLOWING(2) | FOLLOWING(3)),

	BINARY__INSTR("set",	0x2d, REGISTER | POINTER, FIRST_NIBBLE | OFFSET_FOLLOWING(1), REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x2e, REGISTER | POINTER, FIRST_NIBBLE | OFFSET_FOLLOWING(1), REGISTER | POINTER, SECOND_NIBBLE | OFFSET_FOLLOWING(2)),

	BINARY__INSTR("set",	0x2f, REGISTER | POINTER, FIRST_NIBBLE | OFFSET_FOLLOWING(1), S_REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x30, REGISTER | POINTER, FIRST_NIBBLE | OFFSET_FOLLOWING(1), S_REGISTER | POINTER, SECOND_NIBBLE | OFFSET_FOLLOWING(2)),
	
	
	BINARY__INSTR("set",	0x31, S_REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("set",	0x32, S_REGISTER, FIRST_NIBBLE, CONSTANT | POINTER, FOLLOWING(1)),

	BINARY__INSTR("set",	0x33, S_REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x34, S_REGISTER, FIRST_NIBBLE, REGISTER | POINTER, SECOND_NIBBLE | OFFSET_FOLLOWING(1)),

	BINARY__INSTR("set",	0x35, S_REGISTER, FIRST_NIBBLE, S_REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x36, S_REGISTER, FIRST_NIBBLE, S_REGISTER | POINTER, SECOND_NIBBLE | OFFSET_FOLLOWING(1)),

	BINARY__INSTR("set",	0x37, S_REGISTER | POINTER, FIRST_NIBBLE | OFFSET_FOLLOWING(1), CONSTANT, FOLLOWING(2)),
	BINARY__INSTR("set",	0x38, S_REGISTER | POINTER, FIRST_NIBBLE | OFFSET_FOLLOWING(1), CONSTANT | POINTER, FOLLOWING(2)),

	BINARY__INSTR("set",	0x39, S_REGISTER | POINTER, FIRST_NIBBLE | OFFSET_FOLLOWING(1), REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x3a, S_REGISTER | POINTER, FIRST_NIBBLE | OFFSET_FOLLOWING(1), REGISTER | POINTER, SECOND_NIBBLE | OFFSET_FOLLOWING(2)),

	BINARY__INSTR("set",	0x3b, S_REGISTER | POINTER, FIRST_NIBBLE | OFFSET_FOLLOWING(1), S_REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("set",	0x3c, S_REGISTER | POINTER, FIRST_NIBBLE | OFFSET_FOLLOWING(1), S_REGISTER | POINTER, SECOND_NIBBLE | OFFSET_FOLLOWING(2)),

	//**ALU**//
	UNARY___INSTR("neg",	0x3d, REGISTER, FIRST_NIBBLE | SECOND_NIBBLE),
	UNARY___INSTR("inc",	0x3e, REGISTER, FIRST_NIBBLE | SECOND_NIBBLE),
	UNARY___INSTR("dec",	0x3f, REGISTER, FIRST_NIBBLE | SECOND_NIBBLE),
	UNARY___INSTR("sgn",	0x40, REGISTER, FIRST_NIBBLE | SECOND_NIBBLE),
	UNARY___INSTR("not",	0x41, REGISTER, FIRST_NIBBLE | SECOND_NIBBLE),
	UNARY___INSTR("lshift",	0x42, REGISTER, FIRST_NIBBLE | SECOND_NIBBLE),
	UNARY___INSTR("rshift",	0x43, REGISTER, FIRST_NIBBLE | SECOND_NIBBLE),
	
	BINARY__INSTR("neg",	0x44, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("inc",	0x45, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("dec",	0x46, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("sgn",	0x47, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("not",	0x48, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("lshift",	0x49, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("rshift",	0x4a, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	
	BINARY__INSTR("add",	0x4b, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("sub",	0x4c, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),	
	BINARY__INSTR("mul",	0x4d, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("ucmp",	0x4e, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("cmp",	0x4f, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("and",	0x50, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("or",		0x51, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("xor",	0x52, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	BINARY__INSTR("shift",	0x53, REGISTER, FIRST_NIBBLE, CONSTANT, FOLLOWING(1)),
	
	TERNARY_INSTR("add",	0x54, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("sub",	0x55, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),	
	TERNARY_INSTR("mul",	0x56, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("ucmp",	0x57, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("cmp",	0x58, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("and",	0x59, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("or",		0x5a, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("xor",	0x5b, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	TERNARY_INSTR("shift",	0x5c, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, CONSTANT, FOLLOWING(1)),
	
	BINARY__INSTR("add",	0x5d, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("sub",	0x5e, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),	
	BINARY__INSTR("mul",	0x5f, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("ucmp",	0x60, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("cmp",	0x61, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("and",	0x62, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("or",		0x63, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("xor",	0x64, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("shift",	0x65, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	
	TERNARY_INSTR("add",	0x66, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, REGISTER, FOLLOWING(1)),
	TERNARY_INSTR("sub",	0x67, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, REGISTER, FOLLOWING(1)),	
	TERNARY_INSTR("mul",	0x68, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, REGISTER, FOLLOWING(1)),
	TERNARY_INSTR("ucmp",	0x69, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, REGISTER, FOLLOWING(1)),
	TERNARY_INSTR("cmp",	0x6a, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, REGISTER, FOLLOWING(1)),
	TERNARY_INSTR("and",	0x6b, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, REGISTER, FOLLOWING(1)),
	TERNARY_INSTR("or",		0x6c, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, REGISTER, FOLLOWING(1)),
	TERNARY_INSTR("xor",	0x6d, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, REGISTER, FOLLOWING(1)),
	TERNARY_INSTR("shift",	0x6e, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE, REGISTER, FOLLOWING(1)),

	//**stack stuff**//

	// pushes
	NULLARY_INSTR("push",	0x6f),
	UNARY___INSTR("push",	0x70, CONSTANT, FOLLOWING(1)),
	UNARY___INSTR("push",	0x71, CONSTANT | POINTER, OFFSET_FOLLOWING(1)),
	UNARY___INSTR("push",	0x72, REGISTER, FIRST_NIBBLE),
	UNARY___INSTR("push",	0x73, REGISTER | POINTER, FIRST_NIBBLE | OFFSET_FOLLOWING(1)),
	UNARY___INSTR("push",	0x74, S_REGISTER, FIRST_NIBBLE),
	UNARY___INSTR("push",	0x75, S_REGISTER | POINTER, FIRST_NIBBLE | OFFSET_FOLLOWING(1)),

	// pops
	NULLARY_INSTR("pop",	0x76),
	UNARY___INSTR("pop",	0x77, CONSTANT | POINTER, FOLLOWING(1)),
	UNARY___INSTR("pop",	0x78, REGISTER, FIRST_NIBBLE),
	UNARY___INSTR("pop",	0x79, REGISTER | POINTER, FIRST_NIBBLE | OFFSET_FOLLOWING(1)),
	UNARY___INSTR("pop",	0x7a, S_REGISTER, FIRST_NIBBLE),
	UNARY___INSTR("pop",	0x7b, S_REGISTER | POINTER, FIRST_NIBBLE | OFFSET_FOLLOWING(1)),
	
	// function stuff
	UNARY___INSTR("call",	0x7c, CONSTANT, FOLLOWING(1)),
	
	NULLARY_INSTR("return",	0x7d),
	
	// I/O pins
	UNARY___INSTR("pinmode_input",	0x7e, CONSTANT, FIRST_NIBBLE),
	UNARY___INSTR("pinmode_output",	0x7f, CONSTANT, FIRST_NIBBLE),
	
	UNARY___INSTR("pinmode_input",	0x80, REGISTER, FIRST_NIBBLE),
	UNARY___INSTR("pinmode_output",	0x81, REGISTER, FIRST_NIBBLE),
	
	UNARY___INSTR("set_pin_low",	0x82, CONSTANT, FIRST_NIBBLE),
	UNARY___INSTR("set_pin_high",	0x83, CONSTANT, FIRST_NIBBLE),
	
	UNARY___INSTR("set_pin_low",	0x84, REGISTER, FIRST_NIBBLE),
	UNARY___INSTR("set_pin_high",	0x85, REGISTER, FIRST_NIBBLE),
	
	BINARY__INSTR("read_pin",		0x86, CONSTANT, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("write_pin",		0x87, CONSTANT, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	
	BINARY__INSTR("read_pin",		0x88, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	BINARY__INSTR("write_pin",		0x89, REGISTER, FIRST_NIBBLE, REGISTER, SECOND_NIBBLE),
	
	// important stuff
	NULLARY_INSTR("handle_interrupt",		0xfe),
	NULLARY_INSTR("halt_and_catch_fire",	0xff)
};

#define BUFLEN 2048

int is_an_instruction(const char *token)
{
	if (token == NULL)
		return 0;
	int count = 0;
	
	for (int i = 0; i < N_INSTR; i++)
	{
		if (strcmp(dunk_instrs[i].name, token) == 0)
		{
			count++;
		}
	}
	
	return count;
}

char *instruction_valid_parameters_errf(const char *name)
{
	if (name == NULL)
		return NULL;
	
	char *buf = malloc(BUFLEN * sizeof(char));
	
	if (buf == NULL)
		return NULL;
	
	for (int i = 0; i < BUFLEN; i++)
		buf[i] = 0;
	
	int position = 0;
	int count = 0;
	int w_count = 0;
	int indices[N_INSTR];
	
	for (int i = 0; i < N_INSTR; i++)
	{
		if (strcmp(dunk_instrs[i].name, name) == 0)
		{
			indices[count++] = i;
		}
	}
	
	if (count == 0)
		return NULL;
	
	for (int i = 0; i < count; i++)
	{
		if (strcmp(dunk_instrs[indices[i]].name, name) == 0)
		{
			sprintf(&buf[position], "\n\t\t(");
			position = strlen(buf);
			
			for (int j = 0; j < dunk_instrs[indices[i]].n_parameters; j++)
			{
				switch (dunk_instrs[indices[i]].parameter_types[j])
				{
					case CONSTANT:
						sprintf(&buf[position], "constant  ");
						break;
					
					case CONSTANT | POINTER:
						sprintf(&buf[position], "constant* ");
						break;
					
					case REGISTER:
						sprintf(&buf[position], "register  ");
						break;
					
					case REGISTER | POINTER:
						sprintf(&buf[position], "register  ");
						break;
					
					case S_REGISTER:
						sprintf(&buf[position], "sregister ");
						break;
					
					case S_REGISTER | POINTER:
						sprintf(&buf[position], "sregister* ");
						break;
				}
				
				position += 10;
				if (j != dunk_instrs[indices[i]].n_parameters - 1)
				{
					buf[position++] = ',';
					buf[position++] = ' ';
				}
			}
			
			
			buf[position++] = ')';
			if (i != count - 1)
				buf[position++] = ',';
			
			
			if (count > 1 && i == count - 2)
			{
				sprintf(&buf[position], " or");
				position += 3;
			}
			
			
			w_count++;
		}
	}
	
	return buf;
}
