#ifndef DUNKPROG_INSTR_H
#define DUNKPROG_INSTR_H

#define CHILL 											0x00
#define GOTO_C 											0x01
#define GOTO_IF_ZERO_R_C 								0x02
#define GOTO_IF_NONZERO_R_C 							0x03
#define GOTO_IF_NEGATIVE_R_C 							0x04
#define GOTO_IF_NONNEGATIVE_R_C 						0x05
#define GOTO_IF_POSITIVE_R_C 							0x06
#define GOTO_IF_NONPOSITIVE_R_C 						0x07
#define GOTO_IF_EQUAL_R_R_C 							0x08
#define GOTO_IF_UNEQUAL_R_R_C 							0x09
#define GOTO_IF_LESS_R_R_C 								0x0a
#define GOTO_IF_GREATER_R_R_C 							0x0b
#define GOTO_IF_LEQ_R_R_C 								0x0c
#define GOTO_IF_GEQ_R_R_C 								0x0d
#define GOTO_IF_EQUAL_R_C_C 							0x0e
#define GOTO_IF_UNEQUAL_R_C_C 							0x0f
#define GOTO_IF_LESS_R_C_C 								0x10
#define GOTO_IF_GREATER_R_C_C 							0x11
#define GOTO_IF_LEQ_R_C_C 								0x12
#define GOTO_IF_GEQ_R_C_C 								0x13
#define GOTO_IF_LESS_UNSGN_R_R_C 						0x14
#define GOTO_IF_GREATER_UNSGN_R_R_C 					0x15
#define GOTO_IF_LEQ_UNSGN_R_R_C 						0x16
#define GOTO_IF_GEQ_UNSGN_R_R_C 						0x17
#define GOTO_IF_EQUAL_UNSGN_R_C_C 						0x18
#define GOTO_IF_UNEQUAL_UNSGN_R_C_C 					0x19
#define GOTO_IF_LESS_UNSGN_R_C_C 						0x1a
#define GOTO_IF_GREATER_UNSGN_R_C_C 					0x1b
#define GOTO_IF_LEQ_UNSGN_R_C_C 						0x1c
#define GOTO_IF_GEQ_UNSGN_R_C_C 						0x1d
#define SWAP_R_R 										0x1e
#define SET_PC_C 										0x1f
#define SET_PC_PC 										0x20
#define SET_PC_R 										0x21
#define SET_PC_PR 										0x22
#define SET_PC_SR 										0x23
#define SET_PC_PSR 										0x24
#define SET_R_C 										0x25
#define SET_R_PC 										0x26
#define SET_R_R 										0x27
#define SET_R_PR 										0x28
#define SET_R_SR 										0x29
#define SET_R_PSR 										0x2a
#define SET_PR_C 										0x2b
#define SET_PR_PC 										0x2c
#define SET_PR_R 										0x2d
#define SET_PR_PR 										0x2e
#define SET_PR_SR 										0x2f
#define SET_PR_PSR 										0x30
#define SET_SR_C 										0x31
#define SET_SR_PC 										0x32
#define SET_SR_R 										0x33
#define SET_SR_PR 										0x34
#define SET_SR_SR 										0x35
#define SET_SR_PSR 										0x36
#define SET_PSR_C 										0x37
#define SET_PSR_PC 										0x38
#define SET_PSR_R 										0x39
#define SET_PSR_PR 										0x3a
#define SET_PSR_SR 										0x3b
#define SET_PSR_PSR 									0x3c
#define NEG_R 											0x3d
#define INC_R 											0x3e
#define DEC_R 											0x3f
#define SGN_R 											0x40
#define NOT_R 											0x41
#define LSHIFT_R 										0x42
#define RSHIFT_R 										0x43
#define NEG_R_R 										0x44
#define INC_R_R 										0x45
#define DEC_R_R 										0x46
#define SGN_R_R 										0x47
#define NOT_R_R 										0x48
#define LSHIFT_R_R 										0x49
#define RSHIFT_R_R 										0x4a
#define ADD_R_C 										0x4b
#define SUB_R_C 										0x4c
#define MUL_R_C 										0x4d
#define UCMP_R_C 										0x4e
#define CMP_R_C 										0x4f
#define AND_R_C 										0x50
#define OR_R_C 											0x51
#define XOR_R_C 										0x52
#define SHIFT_R_C 										0x53
#define ADD_R_R_C 										0x54
#define SUB_R_R_C 										0x55
#define MUL_R_R_C 										0x56
#define UCMP_R_R_C 										0x57
#define CMP_R_R_C 										0x58
#define AND_R_R_C 										0x59
#define OR_R_R_C 										0x5a
#define XOR_R_R_C 										0x5b
#define SHIFT_R_R_C 									0x5c
#define ADD_R_R 										0x5d
#define SUB_R_R 										0x5e
#define MUL_R_R 										0x5f
#define UCMP_R_R 										0x60
#define CMP_R_R 										0x61
#define AND_R_R 										0x62
#define OR_R_R 											0x63
#define XOR_R_R 										0x64
#define SHIFT_R_R 										0x65
#define ADD_R_R_R 										0x66
#define SUB_R_R_R 										0x67
#define MUL_R_R_R 										0x68
#define UCMP_R_R_R 										0x69
#define CMP_R_R_R 										0x6a
#define AND_R_R_R 										0x6b
#define OR_R_R_R 										0x6c
#define XOR_R_R_R 										0x6d
#define SHIFT_R_R_R 									0x6e
#define PUSH 											0x6f
#define PUSH_C 											0x70
#define PUSH_PC 										0x71
#define PUSH_R 											0x72
#define PUSH_PR 										0x73
#define PUSH_SR 										0x74
#define PUSH_PSR 										0x75
#define POP 											0x76
#define POP_PC 											0x77
#define POP_R 											0x78
#define POP_PR 											0x79
#define POP_SR 											0x7a
#define POP_PSR 										0x7b
#define CALL_C 											0x7c
#define RETURN 											0x7d
#define PINMODE_INPUT_C 								0x7e
#define PINMODE_OUTPUT_C 								0x7f
#define PINMODE_INPUT_R 								0x80
#define PINMODE_OUTPUT_R 								0x81
#define SET_PIN_LOW_C 									0x82
#define SET_PIN_HIGH_C 									0x83
#define SET_PIN_LOW_R 									0x84
#define SET_PIN_HIGH_R 									0x85
#define READ_PIN_C_R 									0x86
#define WRITE_PIN_C_R 									0x87
#define READ_PIN_R_R 									0x88
#define WRITE_PIN_R_R 									0x89
#define PRINTS_C_C 										0x8a
#define PRINTS_PR_C 									0x8b
#define SYSCALL_C 										0xfd
#define HANDLE_INTERRUPT 								0xfe
#define HALT_AND_CATCH_FIRE 							0xff

#endif
