#ifndef DUNKPROG_INSTR_H
#define DUNKPROG_INSTR_H

#define CHILL 											0x00
#define GOTO_C 											0x01
#define GOTO_IF_ZERO_R_C 								0x02
#define GOTO_IF_NONZERO_R_C 							0x03
#define GOTO_IF_NEGATIVE_R_C 							0x04
#define GOTO_IF_NONNEGATIVE_R_C 						0x05
#define GOTO_IF_POSITIVE_R_C 							0x06
#define GOTO_IF_NONPOSITIVE_R_C 						0x07
#define GOTO_IF_EQUAL_R_R_C 							0x08
#define GOTO_IF_UNEQUAL_R_R_C 							0x09
#define GOTO_IF_LESS_R_R_C 								0x0a
#define GOTO_IF_GREATER_R_R_C 							0x0b
#define GOTO_IF_LEQ_R_R_C 								0x0c
#define GOTO_IF_GEQ_R_R_C 								0x0d
#define GOTO_IF_EQUAL_R_C_C 							0x0e
#define GOTO_IF_UNEQUAL_R_C_C 							0x0f
#define GOTO_IF_LESS_R_C_C 								0x10
#define GOTO_IF_GREATER_R_C_C 							0x11
#define GOTO_IF_LEQ_R_C_C 								0x12
#define GOTO_IF_GEQ_R_C_C 								0x13
#define GOTO_IF_LESS_UNSGN_R_R_C 						0x14
#define GOTO_IF_GREATER_UNSGN_R_R_C 					0x15
#define GOTO_IF_LEQ_UNSGN_R_R_C 						0x16
#define GOTO_IF_GEQ_UNSGN_R_R_C 						0x17
#define GOTO_IF_EQUAL_UNSGN_R_C_C 						0x18
#define GOTO_IF_UNEQUAL_UNSGN_R_C_C 					0x19
#define GOTO_IF_LESS_UNSGN_R_C_C 						0x1a
#define GOTO_IF_GREATER_UNSGN_R_C_C 					0x1b
#define GOTO_IF_LEQ_UNSGN_R_C_C 						0x1c
#define GOTO_IF_GEQ_UNSGN_R_C_C 						0x1d
#define SWAP_R_R 										0x1e
#define SET_PC_C 										0x1f
#define SET_PC_PC 										0x20
#define SET_PC_R 										0x21
#define SET_PC_PR 										0x22
#define SET_PC_PRO 										0x23
#define SET_PC_SR 										0x24
#define SET_PC_PSR 										0x25
#define SET_PC_PSRO 									0x26
#define SET_R_C 										0x27
#define SET_R_PC 										0x28
#define SET_R_R 										0x29
#define SET_R_PR 										0x2a
#define SET_R_PRO 										0x2b
#define SET_R_SR 										0x2c
#define SET_R_PSR 										0x2d
#define SET_R_PSRO 										0x2e
#define SET_PR_C 										0x2f
#define SET_PR_PC 										0x30
#define SET_PR_R 										0x31
#define SET_PR_PR 										0x32
#define SET_PR_PRO 										0x33
#define SET_PR_SR 										0x34
#define SET_PR_PSR 										0x35
#define SET_PR_PSRO 									0x36
#define SET_PRO_C 										0x37
#define SET_PRO_PC 										0x38
#define SET_PRO_R 										0x39
#define SET_PRO_PR 										0x3a
#define SET_PRO_PRO 									0x3b
#define SET_PRO_SR 										0x3c
#define SET_PRO_PSR 									0x3d
#define SET_PRO_PSRO 									0x3e
#define SET_SR_C 										0x3f
#define SET_SR_PC 										0x40
#define SET_SR_R 										0x41
#define SET_SR_PR 										0x42
#define SET_SR_PRO 										0x43
#define SET_SR_SR 										0x44
#define SET_SR_PSR 										0x45
#define SET_SR_PSRO 									0x46
#define SET_PSR_C 										0x47
#define SET_PSR_PC 										0x48
#define SET_PSR_R 										0x49
#define SET_PSR_PR 										0x4a
#define SET_PSR_PRO 									0x4b
#define SET_PSR_SR 										0x4c
#define SET_PSR_PSR 									0x4d
#define SET_PSR_PSRO 									0x4e
#define SET_PSRO_C 										0x4f
#define SET_PSRO_PC 									0x50
#define SET_PSRO_R 										0x51
#define SET_PSRO_PR 									0x52
#define SET_PSRO_PRO 									0x53
#define SET_PSRO_SR 									0x54
#define SET_PSRO_PSR 									0x55
#define SET_PSRO_PSRO 									0x56
#define NEG_R 											0x57
#define INC_R 											0x58
#define DEC_R 											0x59
#define SGN_R 											0x5a
#define NOT_R 											0x5b
#define LSHIFT_R 										0x5c
#define RSHIFT_R 										0x5d
#define NEG_R_R 										0x5e
#define INC_R_R 										0x5f
#define DEC_R_R 										0x60
#define SGN_R_R 										0x61
#define NOT_R_R 										0x62
#define LSHIFT_R_R 										0x63
#define RSHIFT_R_R 										0x64
#define ADD_R_C 										0x65
#define SUB_R_C 										0x66
#define MUL_R_C 										0x67
#define UCMP_R_C 										0x68
#define CMP_R_C 										0x69
#define AND_R_C 										0x6a
#define OR_R_C 											0x6b
#define XOR_R_C 										0x6c
#define SHIFT_R_C 										0x6d
#define ADD_R_R_C 										0x6e
#define SUB_R_R_C 										0x6f
#define MUL_R_R_C 										0x70
#define UCMP_R_R_C 										0x71
#define CMP_R_R_C 										0x72
#define AND_R_R_C 										0x73
#define OR_R_R_C 										0x74
#define XOR_R_R_C 										0x75
#define SHIFT_R_R_C 									0x76
#define ADD_R_R 										0x77
#define SUB_R_R 										0x78
#define MUL_R_R 										0x79
#define UCMP_R_R 										0x7a
#define CMP_R_R 										0x7b
#define AND_R_R 										0x7c
#define OR_R_R 											0x7d
#define XOR_R_R 										0x7e
#define SHIFT_R_R 										0x7f
#define ADD_R_R_R 										0x80
#define SUB_R_R_R 										0x81
#define MUL_R_R_R 										0x82
#define UCMP_R_R_R 										0x83
#define CMP_R_R_R 										0x84
#define AND_R_R_R 										0x85
#define OR_R_R_R 										0x86
#define XOR_R_R_R 										0x87
#define SHIFT_R_R_R 									0x88
#define PUSH 											0x89
#define PUSH_C 											0x8a
#define PUSH_PC 										0x8b
#define PUSH_R 											0x8c
#define PUSH_PR 										0x8d
#define PUSH_PRO 										0x8e
#define PUSH_SR 										0x8f
#define PUSH_PSR 										0x90
#define PUSH_PSRO 										0x91
#define POP 											0x92
#define POP_PC 											0x93
#define POP_R 											0x94
#define POP_PR 											0x95
#define POP_PRO 										0x96
#define POP_SR 											0x97
#define POP_PSR 										0x98
#define POP_PSRO 										0x99
#define CALL_C 											0x9a
#define RETURN 											0x9b
#define PINMODE_INPUT_C 								0x9c
#define PINMODE_OUTPUT_C 								0x9d
#define PINMODE_INPUT_R 								0x9e
#define PINMODE_OUTPUT_R 								0x9f
#define SET_PIN_LOW_C 									0xa0
#define SET_PIN_HIGH_C 									0xa1
#define SET_PIN_LOW_R 									0xa2
#define SET_PIN_HIGH_R 									0xa3
#define READ_PIN_C_R 									0xa4
#define WRITE_PIN_C_R 									0xa5
#define READ_PIN_R_R 									0xa6
#define WRITE_PIN_R_R 									0xa7
#define HANDLE_INTERRUPT 								0xfe // unimplemented
#define HALT_AND_CATCH_FIRE 							0xff

#endif
